FROM python:3.7
MAINTAINER Carlo Butelli <c.butelli@nxchange.com>

# set working directory
ADD . /code
WORKDIR /code

# add app
COPY requirements /code/requirements

RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements/prod.txt
RUN pip3 install gunicorn

EXPOSE 8080

COPY . /code

# run server
RUN chmod 755 /code/entrypoint-dev.sh
ENTRYPOINT ["/code/entrypoint-dev.sh"]
CMD ["uwsgi", "--uid", "www-data", "--gid", "www-data", "--need-app", "--logformat", "[%(ltime)] [UWSGI] \"%(method) %(uri) %(proto)\" %(status) %(size) \"%(referer)\" \"%(uagent)\""]